---
- name: Ensure that the chrony package is installed
  tags: chrony
  become: true
  yum:
    name: chrony
    state: present
  register: chrony_yum

- block:
    - name: Applying chrony.conf and sysconfig configurations
      tags: chrony
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      notify: restart chronyd
      with_items:
        - { src: chrony.conf.j2, dest: /etc/chrony.conf, mode: 0644 }
        - { src: chronyd.sysconfig.j2, dest: /etc/sysconfig/chronyd, mode: 0644 }

    - name: Enable and start the chronyd service on boot
      service:
        enabled: yes
        name: chronyd
        state: started
  tags: chrony
  become: true
  when: chrony_yum|success
...
