---
- name: Install chrony package
  tags: chrony
  yum: name=chrony
       state=present
       update_cache=yes
  register: chrony_yum

- block:
    - name: Configure chrony.conf
      template: src=chrony.conf.j2
                dest=/etc/chrony.conf
                owner=root
                group=root
                mode=0644
      notify: restart chronyd
    - name: Enable and start the chronyd service
      service: name=chronyd
               enabled=yes
               state=started
  tags: chrony
  when: chrony_yum|success

