---
- name: Ensure that the chrony package is installed
  tags: chrony
  become: true
  yum:
    name: chrony
    state: present
  register: chrony_yum

- block:
    - name: Applying chrony.conf configurations
      tags: chrony
      template:
        src: chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: 0644
      notify: restart chronyd

    - name: Enable and start the chronyd service on boot
      service:
        enabled: yes
        name: chronyd
        state: started
  tags: chrony
  become: true
  when: chrony_yum|success
...
